# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Watcha-Task' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Watcha-Task

pod 'Alamofire', '~> 5.4.1'
pod 'Kingfisher', '~> 5.15.8'
pod 'SwiftyJSON', '~> 5.0.0'
end
